version: "3.9"

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      - DD_API_KEY=${DD_API_KEY}

    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"    # pprof extension
      - "1234:1234"    # OTLP -> Prometheus exported metrics
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP http receiver
      - "8888:8888"    # Prometheus metrics exposed by the collector
      - "8889:8889"    # Prometheus exporter metrics
      - "13133:13133"  # health_check extension
      - "55679:55679"  # zpages extension
    depends_on:
      - jaeger-all-in-one

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
