receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

exporters:
  prometheus:
    endpoint: "0.0.0.0:1234"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  datadog:
    api:
      site: us5.datadoghq.com
      key: ${env:DD_API_KEY}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, datadog]
