// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: orders_service.proto

package protog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOrderRequest) Reset() {
	*x = FindOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderRequest) ProtoMessage() {}

func (x *FindOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderRequest.ProtoReflect.Descriptor instead.
func (*FindOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_service_proto_rawDescGZIP(), []int{0}
}

func (x *FindOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Quote  float32 `protobuf:"fixed32,3,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *FindOrderResponse) Reset() {
	*x = FindOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderResponse) ProtoMessage() {}

func (x *FindOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderResponse.ProtoReflect.Descriptor instead.
func (*FindOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FindOrderResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FindOrderResponse) GetQuote() float32 {
	if x != nil {
		return x.Quote
	}
	return 0
}

type SendOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Quote  float32 `protobuf:"fixed32,2,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *SendOrderRequest) Reset() {
	*x = SendOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderRequest) ProtoMessage() {}

func (x *SendOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderRequest.ProtoReflect.Descriptor instead.
func (*SendOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendOrderRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendOrderRequest) GetQuote() float32 {
	if x != nil {
		return x.Quote
	}
	return 0
}

type SendOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SendOrderResponse) Reset() {
	*x = SendOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderResponse) ProtoMessage() {}

func (x *SendOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderResponse.ProtoReflect.Descriptor instead.
func (*SendOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_orders_service_proto protoreflect.FileDescriptor

var file_orders_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x64, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51,
	0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x22, 0x40, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x79, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x46, 0x69, 0x6e,
	0x64, 0x12, 0x14, 0x2e, 0x64, 0x64, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x64, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x64, 0x64, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64,
	0x64, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x75, 0x63, 0x61, 0x73, 0x6d, 0x6c, 0x73, 0x2f, 0x64, 0x64, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orders_service_proto_rawDescOnce sync.Once
	file_orders_service_proto_rawDescData = file_orders_service_proto_rawDesc
)

func file_orders_service_proto_rawDescGZIP() []byte {
	file_orders_service_proto_rawDescOnce.Do(func() {
		file_orders_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_service_proto_rawDescData)
	})
	return file_orders_service_proto_rawDescData
}

var file_orders_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_service_proto_goTypes = []interface{}{
	(*FindOrderRequest)(nil),  // 0: dd.FindOrderRequest
	(*FindOrderResponse)(nil), // 1: dd.FindOrderResponse
	(*SendOrderRequest)(nil),  // 2: dd.SendOrderRequest
	(*SendOrderResponse)(nil), // 3: dd.SendOrderResponse
}
var file_orders_service_proto_depIdxs = []int32{
	0, // 0: dd.OrdersService.Find:input_type -> dd.FindOrderRequest
	2, // 1: dd.OrdersService.Send:input_type -> dd.SendOrderRequest
	1, // 2: dd.OrdersService.Find:output_type -> dd.FindOrderResponse
	3, // 3: dd.OrdersService.Send:output_type -> dd.SendOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_service_proto_init() }
func file_orders_service_proto_init() {
	if File_orders_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orders_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_service_proto_goTypes,
		DependencyIndexes: file_orders_service_proto_depIdxs,
		MessageInfos:      file_orders_service_proto_msgTypes,
	}.Build()
	File_orders_service_proto = out.File
	file_orders_service_proto_rawDesc = nil
	file_orders_service_proto_goTypes = nil
	file_orders_service_proto_depIdxs = nil
}
